### ISSUE TITLE
Option to disable "auto-resolution"

### ISSUE THREAD

**Issue by Techbrunch** [knennigtri/merge-markdown#51]
It would be great if there was an option to disable the "auto-resolution" feature.

I'm currently using merge-markdown to combine Marp documents and Marp requires relative path.

**Comment by knennigtri** [comment]
Added a quick fix for this though it's not extensively tested, but should work. The only thing that won't work with this mode will be PDF generation `--pdf`. I'll probably come up with a more elegant solution later but for now you need to install the patch version:
```
npm update @knennigtri/merge-markdown@1.0.0-quickfix.0
```
```
merge-markdown -m youManifest.yml --maintainAssetPaths
```
