### ISSUE TITLE
When I have an external link in my markdown file then the execution gets very slow

### ISSUE THREAD

**Issue by earthinversion** [knennigtri/merge-markdown#55]
When I have some external link in my file that contains a "colon", then the execution of the `merge-markdown` becomes very slow (scales with the number of external links I have). 

For example, if I have a line 
```
See the google doc file: [googledoc](https://docs.google.com/)
```
Then it will take very long to finish executing. Please help.

**Comment by knennigtri** [comment]
it's because it's doing link check on all internal and external links.. In version 1.1.0, you can use the `--nolinkcheck` to skip the process.
