### ISSUE TITLE
replace by regex doesnt match all cases

### ISSUE THREAD

**Issue by JOOmsH** [knennigtri/merge-markdown#56]
i tried using

replace:
 (^#): "##"

to change my headers hierarchy.

My files looked like:

```md
# header 1
## header 2
### header 3
```

With the regex i expected as result

```md
## header 1
### header 2
#### header 3
```

Instead I received:

```md
## header 1
## header 2
### header 3
```

**Comment by knennigtri** [comment]
Hmm. That's really weird that it seems to only be working on the first line? I've used the regex quite heavily in my projects and never had an issue. Regardless, here's the method that does the replace: https://github.com/knennigtri/merge-markdown/blob/f121216856e1790ec384bdb4e27031c719ac0d1a/merge.js#L298

According to https://regex101.com/ your regex seems right. Are those 3 lines the only code in the file?

I do have [RegExp.prototype.global](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global) set on the replace method as well.

**Comment by JOOmsH** [comment]
Yes, it replaces only the first '#' of each file. But only if its the first sign of the file-content.

**Comment by knennigtri** [comment]
Could you do a slightly different strategy like:
```
"# ": "##"
```
If not, I'll need to look into this more.

**Comment by JOOmsH** [comment]
Hi, 

it probably wont work, since it multiplies all of the characters. 
For me its fine. I am using an additional script who does the trick for me and formats my merged file. 
I just wanted to report it :)
